FROM python:3.11-slim

WORKDIR /app
COPY . .

RUN pip install fastapi uvicorn psycopg2-binary redis

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8005"]
